CREATE TABLE TEST (
    INT_COL INTEGER,
    CHAR_COL CHAR(20),
    VARCHAR_COL VARCHAR(20),
    CHAR_COL2 CHAR(10)
);

INSERT INTO TEST VALUES (12, 'test', 'test', 'test2');

CREATE PROCEDURE TESTPROC () LANGUAGE JAVA EXTERNAL NAME 'net.sf.jdbcwrappers.trim.TrimmingTest.testProc' PARAMETER STYLE JAVA READS SQL DATA DYNAMIC RESULT SETS 1;
