/*
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package net.sf.jdbcwrappers.log;

import java.sql.ResultSet;
import java.sql.SQLException;

import net.sf.jdbcwrappers.StatementWrapper;

public class LoggingStatementWrapper extends StatementWrapper {
    private final Logger logger;
    private final boolean prettyPrint;
    
    public LoggingStatementWrapper(Logger logger, LoggingConfiguration configuration) {
        this.logger = logger;
        prettyPrint = configuration.isPrettyPrintSqlStatements();
    }

    private void log(String method, String sql) {
        logger.log(this, method, sql, prettyPrint);
    }
    
    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        log("Statement#execute", sql);
        return super.execute(sql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        log("Statement#execute", sql);
        return super.execute(sql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        log("Statement#execute", sql);
        return super.execute(sql, columnNames);
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        log("Statement#execute", sql);
        return super.execute(sql);
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        log("Statement#executeQuery", sql);
        return super.executeQuery(sql);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        log("Statement#executeUpdate", sql);
        return super.executeUpdate(sql, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        log("Statement#executeUpdate", sql);
        return super.executeUpdate(sql, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        log("Statement#executeUpdate", sql);
        return super.executeUpdate(sql, columnNames);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        log("Statement#executeUpdate", sql);
        return super.executeUpdate(sql);
    }
}
